import type { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "luna-roja",
    name: "Luna roja",
    slug: "luna-roja",
    description: "Arreglo de 50-60 rosas rojas con moño rojo, ideal para declaraciones intensas y entregas nocturnas.",
    price: 1499,
    image: "/images/products/luna-roja-catalogo.jpg",
    tag: "50-60 rosas",
    category: "ramos",
    ingredients: ["Rosas rojas", "Moño rojo", "Base elegante"],
    accentClass: "bg-brand-mauve/15 text-brand-red",
  },
  {
    id: "imperio-rojo",
    name: "Imperio rojo",
    slug: "imperio-rojo",
    description: "Ramo de 100 rosas con color a elegir bajo disponibilidad. Volumen premium para ocasiones grandes.",
    price: 2500,
    image: "/images/products/imperio-rojo-catalogo.jpg",
    tag: "100 rosas",
    category: "ramos",
    ingredients: ["Rosas premium", "Envoltura blanca", "Listón"],
    accentClass: "bg-brand-red/10 text-brand-red",
  },
  {
    id: "aura-floral",
    name: "Aura floral",
    slug: "aura-floral",
    description: "Ramo lleno de vida protagonizado por flores mixtas en tonos suaves y follaje fresco.",
    price: 749,
    image: "/images/products/aura-floral-catalogo.jpg",
    tag: "Mixto",
    category: "ramos",
    ingredients: ["Lilis", "Rosas", "Follaje"],
    accentClass: "bg-brand-beige/45 text-brand-wine",
  },
  {
    id: "planta-orquideas",
    name: "Planta de orquídeas",
    slug: "planta-orquideas",
    description: "Planta de orquídeas con presentación elegante, perfecta para interiores y detalles duraderos.",
    price: 550,
    image: "/images/products/planta-orquideas-catalogo.jpg",
    tag: "Planta",
    category: "plantas",
    ingredients: ["Orquídea", "Maceta", "Cuidado fácil"],
    accentClass: "bg-brand-mauve/20 text-brand-red",
  },
  {
    id: "alimento-floral",
    name: "Alimento floral",
    slug: "alimento-floral",
    description: "Sobre de alimento floral para mantener los arreglos frescos por más tiempo.",
    price: 15,
    image: "/images/products/alimento-floral-catalogo.jpg",
    tag: "Cuidado",
    category: "extras",
    ingredients: ["Nutrientes", "Agua limpia", "Frescura"],
    accentClass: "bg-brand-sage/20 text-brand-green",
  },
  {
    id: "eterno-rojo",
    name: "Eterno rojo",
    slug: "eterno-rojo",
    description: "Una docena de rosas rojas con envoltura suave y acabado romántico para regalar sin dudar.",
    price: 300,
    image: "/images/products/eterno-rojo-catalogo.jpg",
    tag: "12 rosas",
    category: "ramos",
    ingredients: ["Rosas rojas", "Papel rosa", "Listón"],
    accentClass: "bg-brand-beige/50 text-brand-wine",
  },
  {
    id: "pasion-clasica",
    name: "Pasión clásica",
    slug: "pasion-clasica",
    description: "Arreglo floral en jarrón con rosas rojas, follaje y moño para un detalle listo para lucir.",
    price: 789,
    image: "/images/products/pasion-clasica-catalogo.jpg",
    tag: "Con jarrón",
    category: "jarron",
    ingredients: ["Rosas", "Jarrón", "Follaje"],
    accentClass: "bg-brand-sage/20 text-brand-green",
  },
  {
    id: "quinto-encanto",
    name: "Quinto encanto",
    slug: "quinto-encanto",
    description: "5 gerberas con follaje en envoltura rosa, un detalle alegre, fresco y fácil de entregar.",
    price: 499,
    image: "/images/products/quinto-encanto-catalogo.jpg",
    tag: "5 gerberas",
    category: "ramos",
    ingredients: ["Gerberas", "Follaje", "Papel rosa"],
    accentClass: "bg-brand-mauve/15 text-brand-red",
  },
  {
    id: "trio-vibrante",
    name: "Trío vibrante",
    slug: "trio-vibrante",
    description: "Tres gerberas y follaje con presentación colorida para alegrar el día con un detalle pequeño.",
    price: 250,
    image: "/images/products/trio-vibrante-catalogo.jpg",
    tag: "3 gerberas",
    category: "ramos",
    ingredients: ["Gerberas", "Follaje", "Listón rojo"],
    accentClass: "bg-brand-beige/45 text-brand-wine",
  },
  {
    id: "cincuenta-suspiros",
    name: "Cincuenta suspiros",
    slug: "cincuenta-suspiros",
    description: "Ramo con rosas en tonos rojo y blanco, gypsophila y envoltura rosa para un detalle tierno.",
    price: 999,
    image: "/images/products/cincuenta-suspiros-catalogo.jpg",
    tag: "Rosas mixtas",
    category: "ramos",
    ingredients: ["Rosas", "Gypsophila", "Envoltura rosa"],
    accentClass: "bg-brand-beige text-brand-wine",
  },
  {
    id: "sol-sereno",
    name: "Sol sereno",
    slug: "sol-sereno",
    description: "Ramo de un girasol con follaje, envoltura kraft y un acento luminoso para sorprender.",
    price: 150,
    image: "/images/products/sol-sereno-catalogo.jpg",
    tag: "Girasol",
    category: "ramos",
    ingredients: ["Girasol", "Follaje", "Papel kraft"],
    accentClass: "bg-brand-beige/60 text-brand-wine",
  },
  {
    id: "pasion-rose",
    name: "Pasión rose",
    slug: "pasion-rose",
    description: "Arreglo floral de gran formato con rosas y envoltura rosa, pensado para una entrega de impacto.",
    price: 2500,
    image: "/images/products/pasion-rose-catalogo.jpg",
    tag: "Premium",
    category: "ramos",
    ingredients: ["Rosas", "Envoltura rosa", "Moño"],
    accentClass: "bg-brand-red/10 text-brand-red",
  },
  {
    id: "dulce-elegancia",
    name: "Dulce elegancia",
    slug: "dulce-elegancia",
    description: "Arreglo floral con tulipanes blancos, rosas rosas y base en tonos suaves para un regalo fino.",
    price: 1999,
    image: "/images/products/dulce-elegancia-catalogo.jpg",
    tag: "Tulipanes",
    category: "ramos",
    ingredients: ["Tulipanes", "Rosas", "Base rosa"],
    accentClass: "bg-brand-sage/30 text-brand-green",
  },
];
