import type { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "luna-roja",
    name: "Luna roja",
    slug: "luna-roja",
    description: "Arreglo de 50-60 rosas rojas con moño rojo, ideal para declaraciones intensas y entregas nocturnas.",
    price: 1499,
    image: "/images/products/luna-roja-transparent.png",
    // Caja compacta — sujeto centrado en el PNG, ligera subida para equilibrar visualmente
    imageClassName: "w-[74%] -translate-y-6",
    tag: "50-60 rosas",
    category: "ramos",
    ingredients: ["Rosas rojas", "Moño rojo", "Base elegante"],
    accentClass: "bg-brand-mauve/15 text-brand-red",
  },
  {
    id: "imperio-rojo",
    name: "Imperio rojo",
    slug: "imperio-rojo",
    description: "Ramo de 100 rosas con color a elegir bajo disponibilidad. Volumen premium para ocasiones grandes.",
    price: 2500,
    image: "/images/products/imperio-rojo-transparent.png",
    // Abanico ancho — sujeto en la mitad superior del PNG, se baja para centrarlo visualmente
    imageClassName: "w-[88%] translate-y-10",
    tag: "100 rosas",
    category: "ramos",
    ingredients: ["Rosas premium", "Envoltura blanca", "Listón"],
    accentClass: "bg-brand-red/10 text-brand-red",
  },
  {
    id: "aura-floral",
    name: "Aura floral",
    slug: "aura-floral",
    description: "Ramo lleno de vida protagonizado por flores mixtas en tonos suaves y follaje fresco.",
    price: 749,
    image: "/images/products/aura-floral-transparent.png",
    // Ramo alto — bien centrado en el PNG
    imageClassName: "w-[70%] translate-y-2",
    tag: "Mixto",
    category: "ramos",
    ingredients: ["Lilis", "Rosas", "Follaje"],
    accentClass: "bg-brand-beige/45 text-brand-wine",
  },
  {
    id: "planta-orquideas",
    name: "Planta de orquídeas",
    slug: "planta-orquideas",
    description: "Planta de orquídeas con presentación elegante, perfecta para interiores y detalles duraderos.",
    price: 550,
    image: "/images/products/planta-de-orquideas-transparent.png",
    // Planta en maceta — más ancha y compacta
    imageClassName: "w-[65%] translate-y-3",
    tag: "Planta",
    category: "plantas",
    ingredients: ["Orquídea", "Maceta", "Cuidado fácil"],
    accentClass: "bg-brand-mauve/20 text-brand-red",
  },
  {
    id: "alimento-floral",
    name: "Alimento floral",
    slug: "alimento-floral",
    description: "Sobre de alimento floral para mantener los arreglos frescos por más tiempo.",
    price: 15,
    image: "/images/products/almiento-floral-transparent.png",
    // Sobre pequeño — se muestra más chico para dar contexto de tamaño real
    imageClassName: "w-[46%] translate-y-2",
    tag: "Cuidado",
    category: "extras",
    ingredients: ["Nutrientes", "Agua limpia", "Frescura"],
    accentClass: "bg-brand-sage/20 text-brand-green",
  },
  {
    id: "eterno-rojo",
    name: "Eterno rojo",
    slug: "eterno-rojo",
    description: "Una docena de rosas rojas con envoltura suave y acabado romántico para regalar sin dudar.",
    price: 300,
    image: "/images/products/eterno-rojo-transparent.png",
    // Ramo alto con rosas — bien centrado
    imageClassName: "w-[70%] translate-y-2",
    tag: "12 rosas",
    category: "ramos",
    ingredients: ["Rosas rojas", "Papel rosa", "Listón"],
    accentClass: "bg-brand-beige/50 text-brand-wine",
  },
  {
    id: "pasion-clasica",
    name: "Pasión clásica",
    slug: "pasion-clasica",
    description: "Arreglo floral en jarrón con rosas rojas, follaje y moño para un detalle listo para lucir.",
    price: 789,
    image: "/images/products/pasion-clasica-transparent.png",
    // Jarrón con rosas — más estrecho por el jarrón, centrado
    imageClassName: "w-[66%] translate-y-2",
    tag: "Con jarrón",
    category: "jarron",
    ingredients: ["Rosas", "Jarrón", "Follaje"],
    accentClass: "bg-brand-sage/20 text-brand-green",
  },
  {
    id: "quinto-encanto",
    name: "Quinto encanto",
    slug: "quinto-encanto",
    description: "5 gerberas con follaje en envoltura rosa, un detalle alegre, fresco y fácil de entregar.",
    price: 499,
    image: "/images/products/quinto-encanto-transparent.png",
    // Ramo de gerberas — alto y centrado
    imageClassName: "w-[70%] translate-y-2",
    tag: "5 gerberas",
    category: "ramos",
    ingredients: ["Gerberas", "Follaje", "Papel rosa"],
    accentClass: "bg-brand-mauve/15 text-brand-red",
  },
  {
    id: "trio-vibrante",
    name: "Trío vibrante",
    slug: "trio-vibrante",
    description: "Tres gerberas y follaje con presentación colorida para alegrar el día con un detalle pequeño.",
    price: 250,
    image: "/images/products/trio-vibrante-transparent.png",
    // Similar a quinto-encanto — misma escala
    imageClassName: "w-[70%] translate-y-2",
    tag: "3 gerberas",
    category: "ramos",
    ingredients: ["Gerberas", "Follaje", "Listón rojo"],
    accentClass: "bg-brand-beige/45 text-brand-wine",
  },
  {
    id: "cincuenta-suspiros",
    name: "Cincuenta suspiros",
    slug: "cincuenta-suspiros",
    description: "Ramo con rosas en tonos rojo y blanco, gypsophila y envoltura rosa para un detalle tierno.",
    price: 999,
    image: "/images/products/cincuenta-suspiros-transparent.png",
    // Vista cenital / flat-lay — arreglo muy ancho, se muestra más grande
    imageClassName: "w-[88%] translate-y-4",
    tag: "Rosas mixtas",
    category: "ramos",
    ingredients: ["Rosas", "Gypsophila", "Envoltura rosa"],
    accentClass: "bg-brand-beige text-brand-wine",
  },
  {
    id: "sol-sereno",
    name: "Sol sereno",
    slug: "sol-sereno",
    description: "Ramo de un girasol con follaje, envoltura kraft y un acento luminoso para sorprender.",
    price: 150,
    image: "/images/products/sol-sereno-transparent.png",
    // Tallo único y alto — más estrecho para mostrar la proporción real
    imageClassName: "w-[58%] translate-y-3",
    tag: "Girasol",
    category: "ramos",
    ingredients: ["Girasol", "Follaje", "Papel kraft"],
    accentClass: "bg-brand-beige/60 text-brand-wine",
  },
  {
    id: "pasion-rose",
    name: "Pasión rose",
    slug: "pasion-rose",
    description: "Arreglo floral de gran formato con rosas y envoltura rosa, pensado para una entrega de impacto.",
    price: 2500,
    image: "/images/products/pasion-rose-transparent.png",
    // Gran formato — ancho prominente
    imageClassName: "w-[80%] translate-y-4",
    tag: "Premium",
    category: "ramos",
    ingredients: ["Rosas", "Envoltura rosa", "Moño"],
    accentClass: "bg-brand-red/10 text-brand-red",
  },
  {
    id: "dulce-elegancia",
    name: "Dulce elegancia",
    slug: "dulce-elegancia",
    description: "Arreglo floral con tulipanes blancos, rosas rosas y base en tonos suaves para un regalo fino.",
    price: 1999,
    image: "/images/products/dulce-elegancia-transparent.png",
    // Caja con tulipanes altos — centrado, los tulipanes suben por encima
    imageClassName: "w-[72%] translate-y-2",
    tag: "Tulipanes",
    category: "ramos",
    ingredients: ["Tulipanes", "Rosas", "Base rosa"],
    accentClass: "bg-brand-sage/30 text-brand-green",
  },

  // ─── Macetas ──────────────────────────────────────────────────────────────
  {
    id: "maceta-luna",
    name: "Maceta Luna",
    slug: "maceta-luna",
    description: "Maceta cilíndrica alta con acabado estriado, perfecta para plantas verticales y rincones elegantes.",
    price: 280,
    image: "/images/products/macetas/maceta_luna_clean.png",
    imageClassName: "w-[55%] translate-y-2",
    imageBg: "#E2D0C3",
    imageShadow: true,
    tag: "Cerámica",
    category: "macetas",
    ingredients: ["Cerámica", "Acabado estriado", "Altura alta"],
    accentClass: "bg-brand-beige/45 text-brand-wine",
  },
  {
    id: "maceta-nube",
    name: "Maceta Nube",
    slug: "maceta-nube",
    description: "Maceta de tamaño medio con relieve esculpido y base elevada, ideal para plantas frondosas.",
    price: 180,
    image: "/images/products/macetas/maceta_nube_clean.png",
    imageClassName: "w-[68%] translate-y-2",
    imageBg: "#E2D0C3",
    imageShadow: true,
    tag: "Cerámica",
    category: "macetas",
    ingredients: ["Cerámica", "Relieve", "Tamaño medio"],
    accentClass: "bg-brand-mauve/15 text-brand-red",
  },
  {
    id: "maceta-alba",
    name: "Maceta Alba",
    slug: "maceta-alba",
    description: "Maceta compacta con acabado estriado y base ancha, ideal para suculentas y plantas pequeñas.",
    price: 160,
    image: "/images/products/macetas/maceta_alba_clean.png",
    imageClassName: "w-[72%] translate-y-2",
    imageBg: "#E2D0C3",
    imageShadow: true,
    tag: "Cerámica",
    category: "macetas",
    ingredients: ["Cerámica", "Acabado estriado", "Tamaño compacto"],
    accentClass: "bg-brand-sage/20 text-brand-green",
  },
  {
    id: "maceta-brisa",
    name: "Maceta Brisa",
    slug: "maceta-brisa",
    description: "Maceta redondeada con líneas horizontales suaves para un look minimalista y orgánico.",
    price: 194,
    image: "/images/products/macetas/maceta_brisa_clean.png",
    imageClassName: "w-[72%] translate-y-2",
    imageBg: "#E2D0C3",
    imageShadow: true,
    tag: "Cerámica",
    category: "macetas",
    ingredients: ["Cerámica", "Líneas horizontales", "Forma redondeada"],
    accentClass: "bg-brand-beige/55 text-brand-wine",
  },
  {
    id: "maceta-perla",
    name: "Maceta Perla",
    slug: "maceta-perla",
    description: "Maceta baja y ancha con superficie estriada, perfecta para arreglos amplios y suculentas.",
    price: 215,
    image: "/images/products/macetas/maceta_perla_clean.png",
    imageClassName: "w-[72%] translate-y-3",
    imageBg: "#E2D0C3",
    imageShadow: true,
    tag: "Cerámica",
    category: "macetas",
    ingredients: ["Cerámica", "Acabado estriado", "Baja y ancha"],
    accentClass: "bg-brand-mauve/20 text-brand-red",
  },
  {
    id: "maceta-serena",
    name: "Maceta Serena",
    slug: "maceta-serena",
    description: "Maceta tipo copa sobre pedestal con acabado estriado, una pieza decorativa con personalidad.",
    price: 80,
    image: "/images/products/macetas/maceta_serena_clean.png",
    imageClassName: "w-[60%] translate-y-2",
    imageBg: "#E2D0C3",
    imageShadow: true,
    tag: "Cerámica",
    category: "macetas",
    ingredients: ["Cerámica", "Base pedestal", "Acabado estriado"],
    accentClass: "bg-brand-sage/25 text-brand-green",
  },
  {
    id: "maceta-aurora",
    name: "Maceta Aurora",
    slug: "maceta-aurora",
    description: "Maceta lisa de forma cuadrada redondeada con acabado satinado, elegante y atemporal.",
    price: 220,
    image: "/images/products/macetas/maceta_aurora_clean.png",
    imageClassName: "w-[72%] translate-y-2",
    imageBg: "#E2D0C3",
    imageShadow: true,
    tag: "Cerámica",
    category: "macetas",
    ingredients: ["Cerámica", "Acabado liso", "Forma cuadrada"],
    accentClass: "bg-brand-beige/50 text-brand-wine",
  },

  // ─── Jarrones ─────────────────────────────────────────────────────────────
  {
    id: "florero-prisma",
    name: "Florero Prisma",
    slug: "florero-prisma",
    description: "Florero compacto con líneas geométricas suaves, ideal para tallos cortos y arreglos pequeños.",
    price: 62,
    image: "/images/products/jarrones/florero_prisma_transparent.png",
    imageClassName: "w-[60%] translate-y-2",
    imageBg: "#F1E7DF",
    imageShadow: true,
    imageFilter: "drop-shadow(0 8px 12px rgba(70,55,40,0.10))",
    tag: "Cristal",
    category: "jarrones",
    ingredients: ["Cristal", "Forma geométrica", "Tamaño compacto"],
    accentClass: "bg-brand-sage/20 text-brand-green",
  },
  {
    id: "florero-aura",
    name: "Florero Aura",
    slug: "florero-aura",
    description: "Florero alto con silueta esbelta, perfecto para tallos largos y composiciones elegantes.",
    price: 140,
    image: "/images/products/jarrones/florero_aura_transparent.png",
    imageClassName: "w-[55%] translate-y-2",
    imageBg: "#F1E7DF",
    imageShadow: true,
    imageFilter: "drop-shadow(0 8px 12px rgba(70,55,40,0.10))",
    tag: "Cristal",
    category: "jarrones",
    ingredients: ["Cristal", "Silueta alta", "Tallos largos"],
    accentClass: "bg-brand-beige/45 text-brand-wine",
  },
  {
    id: "florero-elisse",
    name: "Florero Elisse",
    slug: "florero-elisse",
    description: "Florero con curvas suaves y forma ovalada, una pieza versátil para cualquier estilo de arreglo.",
    price: 160,
    image: "/images/products/jarrones/florero_elisse_transparent.png",
    imageClassName: "w-[65%] translate-y-2",
    imageBg: "#F1E7DF",
    imageShadow: true,
    imageFilter: "drop-shadow(0 8px 12px rgba(70,55,40,0.10))",
    tag: "Cristal",
    category: "jarrones",
    ingredients: ["Cristal", "Forma ovalada", "Curvas suaves"],
    accentClass: "bg-brand-mauve/15 text-brand-red",
  },
  {
    id: "florero-linea",
    name: "Florero Línea",
    slug: "florero-linea",
    description: "Florero esbelto y alto con líneas verticales, ideal para arreglos minimalistas de gran altura.",
    price: 262,
    image: "/images/products/jarrones/florero_linea_transparent.png",
    imageClassName: "w-[50%] translate-y-2",
    imageBg: "#F1E7DF",
    imageShadow: true,
    imageFilter: "drop-shadow(0 8px 12px rgba(70,55,40,0.10))",
    tag: "Cristal",
    category: "jarrones",
    ingredients: ["Cristal", "Líneas verticales", "Altura premium"],
    accentClass: "bg-brand-beige/55 text-brand-wine",
  },
  {
    id: "florero-siena",
    name: "Florero Siena",
    slug: "florero-siena",
    description: "Florero de tamaño medio con cuello estrecho, perfecto para ramos contenidos y centros de mesa.",
    price: 115,
    image: "/images/products/jarrones/florero_siena_transparent.png",
    imageClassName: "w-[62%] translate-y-2",
    imageBg: "#F1E7DF",
    imageShadow: true,
    imageFilter: "drop-shadow(0 8px 12px rgba(70,55,40,0.10))",
    tag: "Cristal",
    category: "jarrones",
    ingredients: ["Cristal", "Cuello estrecho", "Tamaño medio"],
    accentClass: "bg-brand-sage/25 text-brand-green",
  },
  {
    id: "florero-cleo",
    name: "Florero Cleo",
    slug: "florero-cleo",
    description: "Florero con base ancha y boca recogida, una pieza de carácter para arreglos abundantes.",
    price: 183,
    image: "/images/products/jarrones/florero_cleo_transparent.png",
    imageClassName: "w-[68%] translate-y-2",
    imageBg: "#F1E7DF",
    imageShadow: true,
    imageFilter: "drop-shadow(0 8px 12px rgba(70,55,40,0.10))",
    tag: "Cristal",
    category: "jarrones",
    ingredients: ["Cristal", "Base ancha", "Boca recogida"],
    accentClass: "bg-brand-mauve/20 text-brand-red",
  },
  {
    id: "florero-mila",
    name: "Florero Mila",
    slug: "florero-mila",
    description: "Florero clásico de proporciones balanceadas, ideal para ramos versátiles del día a día.",
    price: 138,
    image: "/images/products/jarrones/florero_mila_transparent.png",
    imageClassName: "w-[62%] translate-y-2",
    imageBg: "#F1E7DF",
    imageShadow: true,
    imageFilter: "drop-shadow(0 8px 12px rgba(70,55,40,0.10))",
    tag: "Cristal",
    category: "jarrones",
    ingredients: ["Cristal", "Forma clásica", "Proporción balanceada"],
    accentClass: "bg-brand-beige/50 text-brand-wine",
  },
  {
    id: "florero-atenea",
    name: "Florero Atenea",
    slug: "florero-atenea",
    description: "Florero estatura premium con presencia escultórica, una pieza protagonista para arreglos especiales.",
    price: 296,
    image: "/images/products/jarrones/florero_atenea_transparent.png",
    imageClassName: "w-[55%] translate-y-2",
    imageBg: "#F1E7DF",
    imageShadow: true,
    imageFilter: "drop-shadow(0 8px 12px rgba(70,55,40,0.10))",
    tag: "Cristal",
    category: "jarrones",
    ingredients: ["Cristal", "Estatura premium", "Pieza escultórica"],
    accentClass: "bg-brand-red/10 text-brand-red",
  },
  {
    id: "florero-perla",
    name: "Florero Perla",
    slug: "florero-perla",
    description: "Florero de silueta redondeada y acabado luminoso, suma elegancia a cualquier arreglo floral.",
    price: 140,
    image: "/images/products/jarrones/florero_perla_transparent.png",
    imageClassName: "w-[65%] translate-y-2",
    imageBg: "#F1E7DF",
    imageShadow: true,
    imageFilter: "drop-shadow(0 8px 12px rgba(70,55,40,0.10))",
    tag: "Cristal",
    category: "jarrones",
    ingredients: ["Cristal", "Silueta redondeada", "Acabado luminoso"],
    accentClass: "bg-brand-mauve/15 text-brand-red",
  },
];
